# ワークフロー名
name: main workflow
on:
  push:
    branches:
      - main
  # schedule:
    # 定期実行する時間 +9:00すると日本時間
    # - cron: '30 6 * * *'

permissions:
  id-token: write
  contents: write

jobs:
  DNS_backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install aws-cli-v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: Configure aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::157094121738:role/hikaru_OIDC_test
          aws-region: ap-northeast-1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jq

      - name: Backup acquisition
        run: |
          if [ '${{ github.event_name }}' == 'schedule' ]; then
            aws route53 list-resource-record-sets --hosted-zone-id Z081066224EVNI6C5559P
            echo "リソースレコードセットのJSONデータ:"
            cat maasapis-com.json
            echo "::set-output name=json_data::$(cat maasapis-com.json | jq -Rsa .)"
          else
            echo "スケジュール以外の処理実行"
          fi

      - name: Json file check
        run: |
          echo "Current directory contents:"
          ls -l

          base_json=($(find . -maxdepth 1 -type f -name "*-maasapis-com.json"))
          if [ ${#base_json[@]} -eq 0 ]; then
            echo "*-maasapis-com.json が存在しません。"
            exit 1
          fi

          echo "Found JSON file(s): ${base_json[*]}"

          # JSONファイルをYAML形式に変換し、一時ファイルに保存
          python tool/UP_convert_yaml.py "${base_json[@]}" maasapis-com.yaml maasapis-com-delete.json maasapis-com-update.json

          # Route 53のリソースレコードセットを削除
          if [ -f maasapis-com-delete.json ]; then
            aws route53 change-resource-record-sets --hosted-zone-id Z081066224EVNI6C5559P --change-batch file://maasapis-com-delete.json
            echo "Route 53 のリソースレコードセットを削除しました。"
            rm maasapis-com-delete.json
          else
            echo "削除対象がない為DELETEをスキップします"
          fi

          # リソースレコードセットの更新
          if [ -f maasapis-com-update.json ]; then
            aws route53 change-resource-record-sets --hosted-zone-id Z081066224EVNI6C5559P --change-batch file://maasapis-com-update.json
            echo "Route 53 のリソースレコードセットを更新しました。"

            # YAMLファイルをリポジトリに追加
            mv maasapis-com.yaml maasapis.com/

            # 一時ファイルを削除してリポジトリからも削除
            for json_file in "${base_json[@]}"; do
              git rm "$json_file"
              echo "$json_file を削除しました"
            done

            git config --local user.email "example@example.com"
            git config --local user.name "example"
            git add maasapis.com/maasapis-com.yaml

            if ! git diff --cached --quiet; then
              git commit -m "Update backup file"
              git push
              echo "git push 完了しました。"
            else
              echo "gitリポジトリ変更がありません"
            fi

            rm maasapis-com-update.json
          else
            echo "maasapis-com-update.json の生成に失敗したかレコード削除後の状態と変化がない為生成されなかった"
            
            # YAMLファイルをリポジトリに追加
            if [ -f maasapis-com.yaml ]; then
              mv maasapis-com.yaml maasapis.com/
              for json_file in "${base_json[@]}"; do
                git rm "$json_file"
                echo "$json_file を削除しました"
              done

              git config --local user.email "example@example.com"
              git config --local user.name "example"
              git add maasapis.com/maasapis-com.yaml

              if ! git diff --cached --quiet; then
                git commit -m "Update backup file"
                git push
                echo "git push 完了しました。"
              else
                echo "変更がありません"
              fi

              rm maasapis-com-update.json
            else
              echo "更新用yamlが見つかりません"
            fi
          fi


