# ワークフロー名
name: main workflow
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  DNS_backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install aws-cli-v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: Configure aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::157094121738:role/hikaru_OIDC_test
          aws-region: ap-northeast-1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jq

      - name: Display current directory contents
        run: |
          echo "Current directory contents:"
          ls -l

      - name: Set variables
        run: |
          echo "Setting variables..."
          echo "HOSTED_ZONE_ID=Z01384972NH9V5QUE4YP5" >> $GITHUB_ENV
          echo "FILE_PATH=maasapis.com/maasapis-com.yaml" >> $GITHUB_ENV

      - name: Fetch previous state
        run: |
          echo "Fetching previous state of $FILE_PATH..."
          git fetch origin ${{ github.event.before }}
          git show ${{ github.event.before }}:"$FILE_PATH" > bf_maasapis-com.yaml
          echo "Previous state of $FILE_PATH saved to bf_maasapis-com.yaml:"
          cat bf_maasapis-com.yaml

      - name: Get current state
        run: |
          echo "Getting the current state of $FILE_PATH..."
          cp "$FILE_PATH" now_maasapis-com.yaml

      - name: Compare states
        id: compare
        run: |
          echo "Comparing previous and current states..."
          if ! diff -q bf_maasapis-com.yaml now_maasapis-com.yaml > /dev/null; then
            echo "Differences found."
            echo "::set-output name=differences::true"
          else
            echo "No differences found."
            echo "::set-output name=differences::false"
          fi

      - name: Process differences
        if: steps.compare.outputs.differences == 'true'
        run: |
          echo "Processing differences..."
          python tool/UP_convert_yaml.py now_maasapis-com.yaml bf_maasapis-com.yaml maasapis-com-delete.json maasapis-com-update.json hikaru-test.maasapis.com.

          # Delete resource records
          if [ -f maasapis-com-delete.json ]; then
            echo "maasapis-com-delete.json contents:"
            cat maasapis-com-delete.json
            aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch file://maasapis-com-delete.json
            echo "Deleted resource record sets from Route 53."
            rm maasapis-com-delete.json
          else
            echo "No records to delete, skipping DELETE."
          fi

          # Update resource records
          if [ -f maasapis-com-update.json ]; then
            aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch file://maasapis-com-update.json
            echo "Updated resource record sets in Route 53."
            rm maasapis-com-update.json
          else
            echo "Failed to generate maasapis-com-update.json or no changes after deletion."
          fi
      # - name: Json file check
      #   run: |
      #     echo "Current directory contents:"
      #     ls -l
      #     # Hosted zone IDを変数に代入z
      #     HOSTED_ZONE_ID="Z01384972NH9V5QUE4YP5"

      #     # 対象ファイルのパス
      #     FILE_PATH="maasapis.com/maasapis-com.yaml"

      #     # 更新前の状態を取得して、bf_maasapis-com.yamlに保存
      #     echo "Fetching previous state of $FILE_PATH..."
      #     git fetch origin ${{ github.event.before }} 
      #     git show ${{ github.event.before }}:"$FILE_PATH"> bf_maasapis-com.yaml

      #     # 更新前の状態を表示（オプション）
      #     echo "Previous state of $FILE_PATH saved to bf_maasapis-com.yaml:"
      #     cat bf_maasapis-com.yaml

      #     # push中のmaasapis-com.yamlを取得    
      #     echo "Getting the current state of $FILE_PATH..."
      #     cp "$FILE_PATH" now_maasapis-com.yaml

      #         # 差分を比較
      #     echo "Comparing previous and current states..."
      #     if ! diff -q bf_maasapis-com.yaml now_maasapis-com.yaml > /dev/null; then
      #       echo "Differences found between bf_maasapis-com.yaml and now_maasapis-com.yaml."
      #     # 更新ファイル、削除ファイルを作成し一時ファイルに保存
      #     # python tool/UP_convert_yaml.py 更新レコード入力ファイル 削除レコードファイル(更新前レコード) 削除用出力json名 更新用出力json名 自身判別用ホストゾーン名
      #       python tool/UP_convert_yaml.py now_maasapis-com.yaml bf_maasapis-com.yaml maasapis-com-delete.json maasapis-com-update.json hikaru-test.maasapis.com.

      #       # Route 53のリソースレコードセットを削除
      #       if [ -f maasapis-com-delete.json ]; then
      #           # ファイルの内容を出力
      #         echo "maasapis-com-delete.jsonの内容:"
      #         cat maasapis-com-delete.json

      #         aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch file://maasapis-com-delete.json
      #         echo "Route 53 のリソースレコードセットを削除しました。"
      #         rm maasapis-com-delete.json
      #       else
      #         echo "削除対象がない為DELETEをスキップします"
      #       fi

      #       # リソースレコードセットの更新
      #       if [ -f maasapis-com-update.json ]; then
      #         aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch file://maasapis-com-update.json
      #         echo "Route 53 のリソースレコードセットを更新しました。"

      #         rm maasapis-com-update.json
      #       else
      #         echo "maasapis-com-update.json の生成に失敗したかレコード削除後の状態と変化がない為生成されなかった"
      #       fi
      #     else
      #       echo "No differences found maasapis-com.yaml."
      #     fi




